apiVersion: v2
appVersion: 25.3.10
description: A helm chart for Tock. Tock is an open conversational AI platform. It's a complete solution to build conversational agents aka bots.Tock can integrate and experiment with both classic and Generative AI (LLM, RAG) models
name: tock
icon: https://doc.tock.ai/tock/assets/images/logo-white.svg
home: https://doc.tock.ai
type: application
version: 0.5.5
sources: 
- https://github.com/theopenconversationkit/tock-helm-chart
- https://github.com/theopenconversationkit

maintainers:
  - name: stephanacquatella

annotations:
  artifacthub.io/category: ai-machine-learning
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Theopenconversationkit Home
      url: https://doc.tock.ai/
    - name: Github
      url: https://github.com/theopenconversationkit/tock
    - name: Documentation
      url: https://doc.tock.ai/tock/master/

dependencies:
- name: mongodb
  version: 14.8.3
  repository : https://charts.bitnami.com/bitnami
  condition: global.deployMongoDb.enabled
  tags: 
    - mongodb

- name: opensearch
  version: 2.21.0
  repository : https://opensearch-project.github.io/helm-charts/
  condition: global.deployOpenSearch.enabled
  tags: 
    - opensearch

- name: postgresql
  version: 13.4.4
  repository : https://charts.bitnami.com/bitnami
  condition: global.deployPgVector.enabled
  tags: 
    - postgres 

- name: opensearch-dashboards
  version: 2.19.0
  repository : https://opensearch-project.github.io/helm-charts/
  condition: global.deployOpenSearch.enabled
  tags: 
    - opensearch
    - dashboard