apiVersion: v2
appVersion: 25.3.3
description: A helm chart for Tock. Tock is an open conversational AI platform. It's a complete solution to build conversational agents aka bots.Tock can integrate and experiment with both classic and Generative AI (LLM, RAG) models
name: tock
icon: https://doc.tock.ai/tock/assets/images/logo-white.svg
home: https://doc.tock.ai
type: application
version: 0.5.1
sources: 
- https://github.com/theopenconversationkit/tock-helm-chart
- https://github.com/theopenconversationkit

maintainers:
  - name: stephanacquatella

dependencies:
- name: mongodb
  #version: 13.6.8
  version: 14.8.3
  repository : https://charts.bitnami.com/bitnami
  condition: global.deployMongoDb.enabled
  tags: 
    - mongodb

- name: opensearch
  version: 2.21.0
  repository : https://opensearch-project.github.io/helm-charts/
  condition: global.deployOpenSearch.enabled
  tags: 
    - opensearch

- name: postgresql
  version: 13.4.4
  repository : https://charts.bitnami.com/bitnami
  condition: global.deployPgVector.enabled
  tags: 
    - postgres 

- name: opensearch-dashboards
  version: 2.19.0
  repository : https://opensearch-project.github.io/helm-charts/
  condition: global.deployOpenSearch.enabled
  tags: 
    - opensearch
    - dashboard