apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-kotlin-compiler'
  labels:
    app.kubernetes.io/name: kotlin-compiler
    app.kubernetes.io/component: kotlin-compiler
    app.kubernetes.io/part-of: tock
    app.kubernetes.io/version: {{ .Chart.Version }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: kotlin-compiler
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/resource: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/component: kotlin-compiler
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/resource: deployment
      annotations:
        {{- with .Values.kotlinCompiler.podAnnotations }}
{{ toYaml . | indent 8 }}
        {{- end }}
    spec:
      {{- include "kotlinCompiler.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.kotlinCompiler.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.kotlinCompiler.podSecurityContext "enabled" | toYaml | nindent 10 }}
      {{- end }}
      {{- with .Values.kotlinCompiler.serviceAccountName }}
      serviceAccountName: {{ . }}
      {{- end }}
      {{- with .Values.kotlinCompiler.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- if .Values.kotlinCompiler.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.kotlinCompiler.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: kotlin-compiler
          image: {{ include "kotlinCompiler.image" . }}
          imagePullPolicy: {{ .Values.kotlinCompiler.image.pullPolicy | default "IfNotPresent" }}
          {{- if .Values.kotlinCompiler.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.kotlinCompiler.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: kotlin-compiler
              containerPort: 8080
          {{- if .Values.kotlinCompiler.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: {{ .Values.kotlinCompiler.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.kotlinCompiler.startupProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.kotlinCompiler.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.kotlinCompiler.startupProbe.failureThreshold }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 180
            timeoutSeconds: 5 # Defaults to 1
            periodSeconds: 20 # Defaults to 10
            failureThreshold: 3 # Defaults to 3
          volumeMounts:
              - mountPath: /tmp
                name: tmp-volume
              {{- with .Values.kotlinCompiler.extraVolumeMounts }}
{{ toYaml . | indent 14 }}
              {{- end }}
          {{- with .Values.kotlinCompiler.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-kotlin-compiler-cfg'
      {{- if .Values.kotlinCompiler.resources }}
          resources: {{- toYaml .Values.kotlinCompiler.resources | nindent 14 }}
      {{- end }}
      volumes:
          - name: tmp-volume
            emptyDir: {}
          {{- with .Values.kotlinCompiler.extraVolumes }}
{{ toYaml . | indent 10 }}
          {{- end }}
    {{- with .Values.kotlinCompiler.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kotlinCompiler.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.kotlinCompiler.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}