global:
  wildcardDomain: rancher.localhost
  deployMongoDb:
    enabled: true
  deployPgVector:
    enabled: true

botApi:
  ingress:
    enabled: true
    ingressClassName: traefik

adminWeb:
  ingress:
    enabled: true
    ingressClassName: traefik


mongodb:
  architecture: "replicaset"
  replicaCount: 1
  auth:
    enabled: false
  persistence:
    enabled: false
    size: 1Gi
  image:   
    repository: xavidop/mongodb
    tag: 7.0.14
#  image:
#    repository: zcube/bitnami-compat-mongodb
#    tag: 6.0.5
  
postgresql:
  architecture: standalone
  auth:
    postgresPassword: secretpassword
    database: postgres
  image:
    repository: onelans/pgvector
    tag: pg16

