global:
  wildcardDomain: rancher.localhost
  deployMongoDb:
    enabled: true

botApi:
  ingress:
    enabled: true
    ingressClassName: traefik

adminWeb:
  ingress:
    enabled: true
    ingressClassName: traefik

mongodb:
  architecture: "replicaset"
  auth:
    enabled: false
  persistence:
    enabled: false
    size: 1Gi
  image:
    repository: xavidop/mongodb
    tag: 7.0.14

