global:
  wildcardDomain: gke.mydomain.com
  deployMongoDb:
    enabled: true

botApi:
  ingress:
    enabled: true
    ingressClassName: gce
    annotations:
      kubernetes.io/ingress.class: "gce"
  service:
    type: NodePort

adminWeb:
  ingress:
    enabled: true
    ingressClassName: gce
    annotations:
      kubernetes.io/ingress.class: "gce"  
  service:
    type: NodePort